# Generated by Django 5.0.6 on 2024-06-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend_app', '0002_remove_employee_details_garnishment_fees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empcode', models.IntegerField(max_length=20)),
                ('email', models.EmailField(max_length=254, verbose_name=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
