# Generated by Django 5.0.6 on 2024-06-18 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attend_app', '0003_email_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email_Data',
        ),
    ]
