# Generated by Django 5.0.6 on 2024-06-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend_app', '0004_delete_email_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='InOutPunchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empcode', models.CharField(max_length=255)),
                ('intime', models.CharField(blank=True, max_length=255, null=True)),
                ('outtime', models.CharField(blank=True, max_length=255, null=True)),
                ('worktime', models.CharField(blank=True, max_length=255, null=True)),
                ('overtime', models.CharField(blank=True, max_length=255, null=True)),
                ('breaktime', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('datestring', models.CharField(max_length=255)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('erl_out', models.CharField(blank=True, max_length=255, null=True)),
                ('late_in', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'count_june_15',
                'unique_together': {('empcode', 'datestring')},
            },
        ),
    ]
