# Generated by Django 5.0.6 on 2024-06-19 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attend_app', '0005_inoutpunchdata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inoutpunchdata',
            table='count_number',
        ),
    ]
