# Generated by Django 5.0.6 on 2024-06-19 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attend_app', '0006_alter_inoutpunchdata_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InOutPunchData',
            new_name='count_number',
        ),
        migrations.AlterUniqueTogether(
            name='count_number',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='count_number',
            table=None,
        ),
    ]
