# Generated by Django 5.0.6 on 2024-06-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend_app', '0007_rename_inoutpunchdata_count_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_details',
            old_name='employee_name',
            new_name='emp_role',
        ),
        migrations.RenameField(
            model_name='employee_details',
            old_name='location',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='employee_details',
            old_name='minimun_wages',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='employee_details',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='employee_details',
            name='employer_id',
        ),
        migrations.RemoveField(
            model_name='employee_details',
            name='net_pay',
        ),
        migrations.RemoveField(
            model_name='employee_details',
            name='pay_cycle',
        ),
        migrations.AddField(
            model_name='employee_details',
            name='emp_address',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_details',
            name='status',
            field=models.CharField(default='WFH', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='empcode',
            field=models.IntegerField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
