# Generated by Django 5.0.6 on 2024-06-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend_app', '0008_rename_employee_name_employee_details_emp_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_details',
            name='empcode',
        ),
        migrations.AddField(
            model_name='employee_details',
            name='emp_code',
            field=models.IntegerField(default='0005', max_length=20, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
