# Generated by Django 5.0.6 on 2024-06-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend_app', '0009_remove_employee_details_empcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='emp_code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
